# Generated by Django 4.1.2 on 2022-10-11 05:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKeys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.TextField()),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
