# Generated by Django 4.1.2 on 2022-10-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickeys',
            name='public_key',
            field=models.TextField(unique=True),
        ),
    ]
